### ISSUE TITLE
サブモニタに配置した時計がフルスクリーンでの動画視聴を解除するとメインモニターに移動してしまう

### ISSUE THREAD

**Issue by arigayas** [owlsperspective/wallclock#1]
WallClock を開発していただきありがとうございます！！

Version 1.1.0を3モニター環境で試しに使ってみましたが、
少し気になった動作があったのでissue報告します。
これって仕様でしょうか？

### 現状：
1. WallClock を起動します。primaryモニターに表示されます。
2. タスクトレイでサブモニタのMonitor1に設定します。
![image](https://github.com/owlsperspective/wallclock/assets/11251874/c9bd8988-14bc-4dbd-b83e-98017311b9c8)
3. WallClock がサブモニタのMonitor1に表示されます。
4. ブラウザでYouTube動画をフルスクリーンで再生します。
5. 動画の再生を止めてフルスクリーンを解除します。
6. WallClock がprimaryモニターに表示されます。

### 私が期待する動作：

6.WallClock がサブモニタのMonitor1に表示されたままになる。

### 使用環境は、
モニターを横に並べて使っています。
横(primaryモニター / FullHD)、縦置き(Monitor 3 / WQHD)、縦置き(Monitor 2 / FullHD)

**Comment by owlsperspective** [comment]
これは確かに期待する動作ではないですね。
フルスクリーンのものがあったらフォームのVisibleをFalseに、なかったらTrueにしているだけで、モニタを移動する動作とは関係ないはずです。
ひょっとしたら選択したモニタのハンドルが無効になってしまっているのかもしれません。調査してみます。
報告ありがとうございます。

**Comment by owlsperspective** [comment]
原因がわかりました。フルスクリーンのものが存在するときにフォームのVisibleをFalseに、なくなったらTrueに、としているため、TrueにしたときにフォームのOnShowが発生しており、ここで再びもろもろ初期化をしてしまい、選択モニタがPrimaryに戻ってしまう、ということでした。

**Comment by owlsperspective** [comment]
Version 1.1.1で修正しました。

**Comment by arigayas** [comment]
修正していただきありがとうございました！
