### ISSUE TITLE
[要望] フルスクリーンの時の表示/非表示を設定出来るようになって欲しい。

### ISSUE THREAD

**Issue by arigayas** [owlsperspective/wallclock#2]
シングルモニターの場合のフルスクリーン時にWallClockの表示があったら邪魔に感じることも多そうですが、
#1 が修正された現在、メインモニターをフルスクリーン表示してサブモニタにWallClockを表示しているんですが、
時間を確認するためにフルスクリーン解除する手間がちょっとなぁと思って、
WallClock が常時表示される機能が欲しくなりました。

タスクトレイの設定項目としては、
- モニタ(M)
-- Monitor 1
-- Monitor 2
- 表示
-- 自動的に消える
-- 常に表示
- 終了

という感じはいかがでしょうか？

**Comment by owlsperspective** [comment]
ポップアップメニューに"フルスクリーンを無視する"を追加しました。
