### ISSUE TITLE
フルスクリーン時に「フルスクリーンを無視」を有効にしても表示されない

### ISSUE THREAD

**Issue by arigayas** [owlsperspective/wallclock#3]
Wall Clock 1.2.1 の動作としてちょっと気になったので報告します。

1. Wall Clock を起動します。
2. PrimaryモニターでWebブラウザを起動します。
3. Webブラウザを(F11キーを押下して)フルスクリーン表示にします。
4. Winキーを押してタスクバーを表示します。
5. タスクトレイにあるWall Clockを右クリックします。
6. 右クリックメニューの「フルスクリーンを無視」をクリックして有効にします。

### 現在の動作
7-a. Wall Clockが表示されませんがフルスクリーンを解除するとWall Clockが表示されます。

### 期待する動作
7-b. フルスクリーンを解除せずにWall Clockが表示される。

**Comment by owlsperspective** [comment]
時間が空いてしまってすいません。
Version 1.2.3でフルスクリーンを無視する設定とフルスクリーンを検出する処理の関係を見直しましたのでお試しください。

**Comment by arigayas** [comment]
期待する動作になっていました！

対応していただきありがとうございます。
あとReadmeファイルの同梱をしていただきありがとうございます。
